# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformanceazure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://studentperformanceazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6bb34f22fe144821b3be900469e6de65 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bf25e9d4fbe34d1ea14f2c26326dc83c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: studentperformanceazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bb34f22fe144821b3be900469e6de65 }}/studentperformance1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformanceazure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_21cd6318dfc8480a838c67d8272d11a2 }}
        images: 'studentperformanceazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bb34f22fe144821b3be900469e6de65 }}/studentperformance1:${{ github.sha }}'